### ISSUE TITLE
The plugin Cannot redirect to the correct page.

### ISSUE THREAD

**Issue by poluanjingtian** [cloudogu/sonar-cas-plugin#1]
After CAS authentication is successful，the url is  http://localhost:9000/cas/validate?ticket=ST-13973-LtcdwPTkwVbDXwFNGYYx-cas01.example.org.
![default](https://user-images.githubusercontent.com/15075699/44331024-096fad00-a49b-11e8-8916-a72a7dc3c29e.png)
How can I solve this problem?

**Comment by ppxl** [comment]
Solved with #2.
