### ISSUE TITLE
scanner maven project throw   ClassNotFoundException

### ISSUE THREAD

**Issue by wxh20114746** [cloudogu/sonar-cas-plugin#21]
when I use mvn sonar:sonar or sonar-scanner command  scanner  maven project,
Console print :java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet

![c69f2f36f12cbac3b6268ea560d84eab](https://user-images.githubusercontent.com/28649555/58265823-03548700-7db3-11e9-8d4a-dc1c998cedf1.png)

**Comment by ppxl** [comment]
Hi, thank you for your patience.

Which release version do you use? It looks like this was solved with #15 in the release [https://github.com/cloudogu/sonar-cas-plugin/releases/tag/v1.0.4](https://github.com/cloudogu/sonar-cas-plugin/releases/tag/v1.0.4)...

Do you mind check if you use the latest version of the Plugin?
