### ISSUE TITLE
html parser throw exception

### ISSUE THREAD

**Issue by commanderback** [cloudogu/sonar-cas-plugin#28]
ERROR web[...][...] The element type "input" must be terminated by the matching end-tag "</input>".

**Comment by ppxl** [comment]
Hi and thank you for request. In order to reproduce your issue I need to know a bit more about your system:

1. Which version of SonarQube did you use?
2. Which version of sonar-cas-plugin did you use?
3. If possible: What is the nature of the request that leads to this error?
   1. like: Browser requests vs REST request
   2. what file/endpoint was requested

Would it be possible to supply any stacktraces, or is this a single log line without any further references?

Thanks in advance

**Comment by commanderback** [comment]
1.Which version of SonarQube did you use?
sonarqube 7.9.5 LTS


2.Which version of sonar-cas-plugin did you use?
sonar-cas-plugin-2.0.2.jar


3. sonarqube cas related config $SONAR_HOME/conf/sonar.properties&nbsp;
sonar.web.sso.enable=true
sonar.web.sso.loginHeader=X-Forwarded-Login
sonar.web.sso.nameHeader=X-Forwarded-Name
sonar.web.sso.emailHeader=X-Forwarded-Email


sonar.security.realm=cas
sonar.authenticator.createUsers=true
sonar.cas.forceCasLogin=true
sonar.cas.protocol=cas3
sonar.cas.casServerUrlPrefix=https://cas.xx.com/&nbsp; &nbsp;&nbsp;
sonar.cas.casServerLoginUrl=https://cas.xx.com/login
sonar.cas.casServerLogoutUrl=https://cas.xx.com/logout
sonar.cas.sonarServerUrl=http://sonarqube:9000
sonar.cas.urlAfterCasRedirectCookieMaxAgeSeconds=300
sonar.cas.sessionStorePath=/opt/app/usr/sonarqube/data/sonarcas/sessionstore
sonar.cas.sessionStore.cleanUpIntervalInSeconds=1800


sonar.cas.rolesAttributes=groups,roles
sonar.cas.fullNameAttribute=displayName
sonar.cas.eMailAttribute=mail
sonar.cas.saml11.toleranceMilliseconds=1000
sonar.cas.disableCertValidation=true




4.If possible: What is the nature of the request that leads to this error?
4.1like: Browser requests vs REST request
I browser http://xx:9000 then input the name/passwd, the browser stop at http://sonarqube:9000/sessions/init/cas?ticket=....
and I check the sonarqube server log file $SONAR_HOME/logs/web.log
2021.01.14 17:17:11 ERROR web[AXcAATOqwIh5Ck86AAAM][o.j.c.c.u.XmlUtils] The element type "input" must be terminated by the matching end-tag "</input&gt;".
org.xml.sax.SAXParseException: The element type "input" must be terminated by the matching end-tag "</input&gt;".
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1683)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2881)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
&nbsp; &nbsp; &nbsp; &nbsp; at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
&nbsp; &nbsp; &nbsp; &nbsp; at org.jasig.cas.client.util.XmlUtils.getTextForElement(XmlUtils.java:192)
at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseProxyGrantingTicketFromResponse(Cas20ServiceTicketValidator.java:117)
&nbsp; &nbsp; &nbsp; &nbsp; at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:88)
&nbsp; &nbsp; &nbsp; &nbsp; at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:201)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.plugins.cas.LoginHandler.handleLogin(LoginHandler.java:62)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.plugins.cas.CasIdentityProvider.init(CasIdentityProvider.java:69)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.handleBaseIdentityProvider(InitFilter.java:106)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.handleProvider(InitFilter.java:80)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.doFilter(InitFilter.java:73)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
&nbsp; &nbsp; &nbsp; &nbsp; at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)
2021.01.14 17:17:11 ERROR web[AXcAATOqwIh5Ck86AAAM][o.s.p.c.CasIdentityProvider] authentication or logout failed
org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.
&nbsp; &nbsp; &nbsp; &nbsp; at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:98)
&nbsp; &nbsp; &nbsp; &nbsp; at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:201)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.plugins.cas.LoginHandler.handleLogin(LoginHandler.java:62)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.plugins.cas.CasIdentityProvider.init(CasIdentityProvider.java:69)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.handleBaseIdentityProvider(InitFilter.java:106)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.handleProvider(InitFilter.java:80)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.authentication.InitFilter.doFilter(InitFilter.java:73)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
&nbsp; &nbsp; &nbsp; &nbsp; at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
&nbsp; &nbsp; &nbsp; &nbsp; at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/java.lang.Thread.run(Thread.java:834)
2021.01.14 17:26:41 DEBUG web[][o.s.p.c.s.SessionStoreCleaner] CAS session writeJwtFile clean up started.
2021.01.14 17:26:41 DEBUG web[][o.s.p.c.s.SessionStoreCleaner] CAS session writeJwtFile clean up finished and removed 0 entries.


what file/endpoint was requested



Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloudogu/sonar-cas-plugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 下午5:22
收件人:&nbsp;"cloudogu/sonar-cas-plugin"<sonar-cas-plugin@noreply.github.com&gt;;
抄送:&nbsp;"神丸"<794608009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudogu/sonar-cas-plugin] html parser throw exception (#28)





 
Hi and thank you for request. In order to reproduce your issue I need to know a bit more about your system:
  
Which version of SonarQube did you use?
 
Which version of sonar-cas-plugin did you use?
 
If possible: What is the nature of the request that leads to this error?  
like: Browser requests vs REST request
 
what file/endpoint was requested
  
  
Would it be possible to supply any stacktraces, or is this a single log line without any further references?
 
Thanks in advance

**Comment by ppxl** [comment]
Hi again,

while I am currently diagnosing your error I found some things in your reply that made me think of a configuration problem.

> 2.Which version of sonar-cas-plugin did you use?
> sonar-cas-plugin-2.0.2.jar

Did you mean `sonar-cas-plugin.2.0.1.jar`? This repo does not contain a release for a version 2.0.2

> 3. sonarqube cas related config $SONAR_HOME/conf/sonar.properties&nbsp;

These two lines of your `sonar.properties` strike me as weird for two reasons:

```
...
sonar.cas.casServerUrlPrefix=https://cas.xx.com/&nbsp; &nbsp;&nbsp;
...
sonar.cas.sonarServerUrl=http://sonarqube:9000
...
```

1. The property `sonar.cas.casServerUrlPrefix` seems to contain non-breaking spaces?: `https://cas.xx.com/&nbsp; &nbsp;&nbsp;`
   - Would you mind and double-check that the property does not contain any whitespaces?
2. the property `sonar.cas.sonarServerUrl` seems to point to a local SonarQube installation while the CAS URL looks like an internet address (`http://sonarqube` vs `https://cas.xx.com`)
   - Both SonarQube installation and CAS server must be able to communicate with each other because of exchanging ticketing information.
   - Could you check if the CAS server has proper connectivity towards the SonarQube server?

Currently I don't have a SonarQube in version 7.9.5 LTS at hand but as a quick-test I checked the constellation 
- SonarQube 7.9.4 with 
- sonar-cas-plugin 2.0.1 without any errors.

I will test with SonarQube 7.9.5 again and will come back to this issue later on.

In the meanwhile: Would you kindly check with my annotations regarding the configuration above?

**Comment by ppxl** [comment]
Hi again.

I was not able to reproduce your error within this installation: 
- SonarQube 7.9.5 and
- sonar-cas-plugin 2.0.1

I noticed something else from which I conclude that your problem is really just a faulty configuration. The error in the stacktrace tells me that an HTML response was tried to be parsed (instead of a CAS ticket in XML). 

> 4.1like: Browser requests vs REST request
> ...
> 2021.01.14 17:17:11 ERROR web[AXcAATOqwIh5Ck86AAAM][o.j.c.c.u.XmlUtils] The element type "input" must be terminated by the matching end-tag "</input&gt;".

The fact that the CAS plugin tries to parse a response with an `input` element is key to my assumption. Usually CAS granting tickets don't contain `<input />` elements, but HTML forms do.

That being said, I suggest to validate the SonarQube configuration. If you want to gain more insights to the faulty HTTP response you could clone the repo and log the CAS response. `org.sonar.plugins.cas.LoginHandler.handleLogin()` would be a good starting point.

**Comment by commanderback** [comment]
Hi，
After confirmation, we use Yale CAS server.&nbsp;
I notice the plugin support Apereo CAS.&nbsp;
so I want to know whether the plugin supports Yale CAS.


Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloudogu/sonar-cas-plugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 晚上7:11
收件人:&nbsp;"cloudogu/sonar-cas-plugin"<sonar-cas-plugin@noreply.github.com&gt;;
抄送:&nbsp;"神丸"<794608009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudogu/sonar-cas-plugin] html parser throw exception (#28)





 
Hi again.
 
I was not able to reproduce your error within this installation:
  
SonarQube 7.9.5 and
 
sonar-cas-plugin 2.0.1
  
I noticed something else from which I conclude that your problem is really just a faulty configuration. The error in the stacktrace tells me that an HTML response was tried to be parsed (instead of a CAS ticket in XML).
  
4.1like: Browser requests vs REST request
 ...
 2021.01.14 17:17:11 ERROR web[AXcAATOqwIh5Ck86AAAM][o.j.c.c.u.XmlUtils] The element type "input" must be terminated by the matching end-tag "</input&gt;".
  
The fact that the CAS plugin tries to parse a response with an input element is key to my assumption. Usually CAS granting tickets don't contain <input /&gt; elements.
 
That being said, I suggest to validate the SonarQube configuration. If you want to gain more insights to the faulty HTTP response you could clone the repo and log the CAS response. org.sonar.plugins.cas.LoginHandler.handleLogin() would be a good starting point.

**Comment by ppxl** [comment]
From what I understand is that University Yale designed the CAS specification and created an initial CAS implementation. After that Yale submitted it to Apereo for proper maintenance.

Speaking for myself, Apereo's CAS implementation is so old that I haven't ever held a Yale implementation in my hands. https://github.com/cloudogu/sonar-cas-plugin from supports only Apereo CAS. It was successfully tested with [CAS 4.0.x](https://apereo.github.io/cas/4.0.x/index.html)

I saw you using the CAS 3 specification, but maybe that was just default values in `sonar.properties`?:
 ```
sonar.cas.protocol=cas3
```

Just so I can take the CAS implementation into consideration which you are using:
1. Which CAS version/binary do you actually use?
1. Can you point me to a download page?

**Comment by ppxl** [comment]
I am closing this issue because it is stale and also because it looks like a configuration fault. Please feel free to reply if there is additional information available.
